Repository Sagar0-0/DsA, pull requests merged in 2022-10, with the labels that each got.

#429 Moved 2 code from home directory to correct folder for better structuring of the repository
  Leetcode/437 Path Sum III/pathSum.cpp
  Leetcode/450 Delete Node in a BST/deleteNode.java
Labels: hacktoberfest-accepted

#440 Create 1155. Number of Dice Rolls With Target Sum.py
  Leetcode/1155. Number of Dice Rolls With Target Sum/1155. Number of Dice Rolls With Target Sum.py
Labels: hacktoberfest-accepted

#441 Create Remove Letter To Equalize Frequency.cpp
  Leetcode/Remove Letter To Equalize Frequency/Remove Letter To Equalize Frequency.cpp
Labels: hacktoberfest-accepted

#438 Minimum characters to be added at front to make string palindrome.java
  GFG/Minimum characters to be added at front to make string palindrome/Minimum characters to be added at front to make string palindrome.java
Labels: hacktoberfest-accepted

#430 GFG problem of the day
  GFG/Minimum characters to be added at front to make string palindrome/Minimum characters to be added at front to make string palindrome.cpp
  GFG/Minimum characters to be added at front to make string palindrome/README.md
Labels: hacktoberfest-accepted

#425 Update Number of Distinct Islands oct1.cpp
  GFG/Number of Distinct Islands/Number of Distinct Islands oct1.cpp
Labels: hacktoberfest-accepted

#472 104-maximum-depth-of-binary-tree
  Leetcode/104-maximum-depth-of-binary-tree/104-maximum-depth-of-binary-tree.cpp
  Leetcode/104-maximum-depth-of-binary-tree/README.md
Labels: hacktoberfest-accepted

#467 LEETCODE QUESTION 2424. Longest Uploaded Prefix ADDED
  Leetcode/2424. Longest Uploaded Prefix/2424. Longest Uploaded Prefix.java
Labels: hacktoberfest-accepted

#466 Number of dice rolls solved with DP
  Leetcode/Number of Dice rolls with target sum/Number of dice rolls.cpp
Labels: hacktoberfest-accepted

#462 Create Search Pattern (Rabin-Karp Algorithm).java
  GFG/Search Pattern (Rabin-Karp Algorithm)/Search Pattern (Rabin-Karp Algorithm).java
Labels: hacktoberfest-accepted

#476 Update README.md
  README.md
Labels: documentation

#482 Modified Numbers and Queries GFG POTD
  GFG/Modified Numbers and Queries/Modified Numbers and Queries.cpp
  GFG/Modified Numbers and Queries/README.md
Labels: hacktoberfest-accepted

#463 Create Spiral Matrix.cpp
  GFG/Spiral Matrix/Spiral Matrix.cpp
Labels: hacktoberfest-accepted

#459 Added solution for Leetcode problem 2095 with readme
  2095-Delete-MiddleNode-LinkedList/DeleteMiddleNodeLinkedlist.java
  2095-Delete-MiddleNode-LinkedList/README.md
Labels: invalid

#457 Java maximal square
  Leetcode/221. Maximal Square/221. Maximal Square.java
Labels: hacktoberfest-accepted

#434 75. Sort Colors
  Leetcode/1304.Find N Unique Integers Sum up to Zero/1304.Find N Unique Integers Sum up to Zero.java
  Leetcode/1304.Find N Unique Integers Sum up to Zero/Notes.md
  Leetcode/1304.Find N Unique Integers Sum up to Zero/README.md
  Leetcode/75.Sort colors/75.Sort-colors.java
  Leetcode/75.Sort colors/Notes.md
  Leetcode/75.Sort colors/README.md
Labels: hacktoberfest-accepted

#450 Added Solution of 3Sum.java
  Leetcode/15. 3Sum/3sum.java
  Leetcode/15. 3Sum/README.md
Labels: hacktoberfest-accepted

#513 Path Sum.java
  Leetcode/112 Path Sum/Path Sum.java
Labels: hacktoberfest-accepted

#508 Count all possible paths from top left to bottom right - GFG POTD
  GFG/Count all possible paths from top left to bottom right/Count all possible paths from top left to bottom right.cpp
  GFG/Count all possible paths from top left to bottom right/README.md
Labels: hacktoberfest-accepted

#507 C++ Solution for Merge K Sorted List
  23-Merge-k-Sorted-Lists/23-Merge-k-Sorted-Lists.cpp
  23-Merge-k-Sorted-Lists/NOTES.md
  23-Merge-k-Sorted-Lists/README.md
Labels: hacktoberfest-accepted

#504 Create Modified Numbers And Queries.java
  GFG/Modified Numbers and Queries/Modified Numbers And Queries.java
Labels: hacktoberfest-accepted

#502 Minimum Time to Make Rope Colorful solved using Greedy
  Leetcode/Minimum time to Make Rope Colorful/Minimum Time to Make Rope Colorful.cpp
  Leetcode/Sort Colors/Sort Colors.cpp
Labels: hacktoberfest-accepted

#499 1578. Minimum Time to Make Rope Colorful.py
  Leetcode/1578. Minimum Time to Make Rope Colorful/1578. Minimum Time to Make Rope Colorful.py
Labels: hacktoberfest-accepted

#496 1252. Cells with Odd Values in a Matrix Leetcode question
  Leetcode/1252. Cells with Odd Values in a Matrix/1252. Cells with Odd Values in a Matrix.java
  Leetcode/1252. Cells with Odd Values in a Matrix/Notes.md
  Leetcode/1252. Cells with Odd Values in a Matrix/README.md
Labels: hacktoberfest-accepted

#495 1217. Minimum Cost to Move Chips to The Same Position
  Leetcode/1217. Minimum Cost to Move Chips to The Same Position/1217. Minimum Cost to Move Chips to The Same Position.java
  Leetcode/1217. Minimum Cost to Move Chips to The Same Position/Notes.md
  Leetcode/1217. Minimum Cost to Move Chips to The Same Position/README.md
Labels: hacktoberfest-accepted

#494 Create Search Pattern (KMP-Algorithm).java
  GFG/Search Pattern (KMP-Algorithm)/Search Pattern (KMP-Algorithm).java
Labels: hacktoberfest-accepted

#492 Modified file name
  GFG/Count all possible paths from top left to bottom right/Count all possible paths from top left to bottom right oc4.cpp
  GFG/Modified Numbers and Queries/Modified Numbers and Queries oc3.cpp
  GFG/Modified Numbers and Queries/Modified Numbers and Queries.cpp
  Leetcode/112 Path Sum/112 Path Sum oc4.cpp
  Leetcode/1578 Minimum Time to Make Rope Colorful/1578 Minimum Time to Make Rope Colorful.cpp
Labels: hacktoberfest-accepted

#490 Create 2428. Maximum Sum of an Hour Glass in LeetCode
  Leetcode/2428. Maximum Sum of an Hour Glass/2428. Maximum Sum of an Hour Glass.cpp
Labels: hacktoberfest-accepted

#520 Create Number of Common Factors in cpp
  Leetcode/2427. Number of Common Factors/2427. Number of Common Factors.cpp
Labels: hacktoberfest-accepted

#522 Create Find the N-th character.cpp
  GFG/Find the N-th character/Find the N-th character.cpp
Labels: hacktoberfest-accepted

#523 Create Delete Node in a Linked List.cpp
  Leetcode/237. Delete Node in a Linked List/Delete Node in a Linked List.cpp
Labels: hacktoberfest-accepted

#524 Create Geek and Strings.java
  GFG/Geek and Strings/Geek and Strings.java
  GFG/Geek and Strings/ReadMe.md
Labels: hacktoberfest-accepted

#525 Create Add one row to tree.java
  Leetcode/623 Add One Row To Tree/Add one row to tree.java
  Leetcode/623 Add One Row To Tree/ReadMe.md
Labels: hacktoberfest-accepted
